package com.hutgin2.meta;

public enum ValueGenerationStrategy {
    /**
     * Field value is not generated
     */
    NONE,
    /**
     * Field value is generated by database itself.
     * Means the same as NONE, but provide some additional info for dao layer
     */
    DATABASE,
    /**
     * Field value is generated by provided class name in {@link com.hutgin2.meta.FieldMeta#getInsertGenerator()} or {@link FieldMeta#getUpdateGenerator()}
     */
    CLASS,
    /**
     * Field value is retrieved from {@link com.hutgin2.meta.FieldMeta#getInsertGenerator()} or {@link com.hutgin2.meta.FieldMeta#getUpdateGenerator()} as string
     */
    DEFAULT_VALUE,
    /**
     * Field value is retrieved from {@link com.hutgin2.meta.FieldMeta#getInsertGenerator()} or {@link com.hutgin2.meta.FieldMeta#getUpdateGenerator()} as stored prcedure call result
     */
    STORED_PROCEDURE
}
